name: GoTest

on: [push]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Setup Golang
        uses: actions/setup-go@v5
        with:
          go-version: '1.23.x'
          cache-dependency-path: go.sum
      - name: Install dependencies
        run: |
          go mod download     
      - name: Run go tests
        run: |
            go test -timeout 30s -race -cover ./...
